### ISSUE TITLE
error on deloy

### ISSUE THREAD

**Issue by subhendukundu** [frandiox/vitedge#14]
When I am running `yarn deploy` after `yarn build`, it yields error.
```
Built successfully, built project size is 757 KiB.
🌀  Using namespace for Workers Site "__cool-workers_sites_assets"
✨  Success
🌀  Uploading site files
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Script startup timed out.\n"
    }
  ],
  "messages": []
}

error Command failed with exit code 1
```

Have you see this issue?
I was talking to Greg about this, he says it is an issue when too many things being initialized as globals
```
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request)
})

const doWork = async () => { /* ... */ }

const handleRequest = async request => {
  const results = await doWork()
  return new Response(JSON.stringify(results))
}
```

vs.
```
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request)
})

const results = /* ... */

const handleRequest = async request => {
  return new Response(JSON.stringify(results))
}
```
The first example (good) does the work in the request/response phase, with just the function declaration in the global state.

The second example (bad) does the work in the global state.

Do you know how to fix this?

**Comment by frandiox** [comment]
@subhendukundu Never saw it before! I don't think we have this kind of global stuff in Vitedge source 🤔 
I would probably start removing/commenting out code from your app until you make it work, and then try to pin point the problem. 

Please update here if you find the solution, or if it's anything related to Vitedge 🙏

**Comment by subhendukundu** [comment]
Umm ya, next is that. Have to start removing code.
Btw, would this create an issue?

```
dist/client/assets/Home.14354298.js      562.83kb / brotli: skipped (large chunk)

(!) Some chunks are larger than 500kb after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
vite v2.1.3 building SSR bundle for production...
[plugin:replace] @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
✓ 39 modules transformed.
dist/ssr/main.js   705.80kb
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
```

when I run `yarn build`

**Comment by frandiox** [comment]
I don't think it's an issue yet, but you have a limit in workers of 1mb, at least until the workers unbound are released.
As the warning says, for the frontend you can try using dynamic imports to do code split.

**Comment by subhendukundu** [comment]
Yup agreed!
I guess the only way to go about this one is "keep removing codes".
I wish they had better error messages on this 🙈

**Comment by subhendukundu** [comment]
I am losing hope on this one :(
I started removing the code. At a point just removing [LIne 237](https://github.com/subhendukundu/cool-bio-analytics/blob/main/src/pages/Home.jsx#L237) and [LIne 238](https://github.com/subhendukundu/cool-bio-analytics/blob/main/src/pages/Home.jsx#L238) is deployed. But when I put 237 line back and removed it back, now the previous deployed it not working either.

Is it because it's not able to upload the dist folder?
If you have few mins, do you think you can try deploying? Maybe just happening with my account?

**Comment by frandiox** [comment]
@subhendukundu I've checked but can't seem to find a solution either. Looks like Wrangler just has a timeout and it dies.
You are embedding huge json files, and also have a lot of css-in-js that run at start, but I'm not sure if that affect.
Perhaps it's related to the map/time dependencies or something like that.

I managed to deploy a lighter version but it is inconsistent, sometimes it deploys and sometimes it doesn't.

Might be something to report to Cloudflare itself. It looks like the "preview" mode works (`wrangler dev`) but it just chokes when uploading static files (`wrangler publish`).


For the time being, if you need to deploy it asap, maybe you can try deploying to Vercel instead. Their edge cache is not bad.  There's an example [here](https://github.com/frandiox/vitedge/blob/master/examples/node-server/index.js) for deploying to pure Node environments.

**Comment by subhendukundu** [comment]
I cant think of much that could create this issue.
Few points:
1. Might be running out of CPU time during start-up execution. I am on a free tire.
2. I have a mix of typescript and javascript. Tho it shouldn't create an issue, but maybe the `.ts` and `.js` could make it sound crazy?

**Comment by subhendukundu** [comment]
Seems something to do with Vitedge?
https://github.com/subhendukundu/cool-bio-analytics-flareact-styled This is working, 98% similar code with flareact. Change a few things to make it work as flareact.
And I really wish to keep using Vitedge cause it really is amazing. So help me out a bit?

**Comment by frandiox** [comment]
@subhendukundu I've checked this for a shameful amount of hours and finally found something in the Webpack configuration that affects it.
I don't think the error is completely gone because it depends on the app dependencies, but it must be reduced now (I could deploy https://analytics-test.zable.workers.dev/).

Update to Vitedge 0.10.5 and add the following to your Webpack config:

```js
const vitedgeWebpack = require("../node_modules/vitedge/webpack.cjs");

const config = vitedgeWebpack();
config.resolve.mainFields = ["browser", "module", "main"];

module.exports = {
  ...config,
};

```

For the record, I tried removing all the internal code that Vitedge adds and it was still failing before changing webpack, so I don't think it is related to Vitedge itself. In fact, I removed all your app code except dependencies (d3, nhost, etc) and still failed randomly.

**Comment by subhendukundu** [comment]
OMG! Thank you so much! I will give this a try! :)
Hope all works fine. Flareact is great but I hate the error messages. Not so great.

**Comment by subhendukundu** [comment]
And its working 😍
I will add a few bunches of codes now. And going to keep an eye on this one.

**Comment by frandiox** [comment]
Happy to hear that! I'll take down my deployment of your website.

As I said, you might see the error randomly, but hope it can be manageable now 👍

**Comment by subhendukundu** [comment]
This error is back again! :(

**Comment by subhendukundu** [comment]
@frandiox I am stuck with this one for a while. Do you think we can fix it anyway?

**Comment by frandiox** [comment]
@subhendukundu I've tried the latest code but get error `Error: Please specify a baseURL. More information at https://docs.nhost.io/libraries/nhost-js-sdk#setup`. And normal development mode also fails with `cannot read split of null` or similar.

>I am stuck with this one for a while. Do you think we can fix it anyway?

I think this error depends on the code of the application and its dependencies so there's no silver bullet for it. I remember removing all the Vitedge code and still getting the error by only keeping the dependencies.

Having a better build process might improve it, though. Right now Vitedge builds first with Vite, and then with Webpack (using Wrangler). Cloudflare recently announced custom builds without Webpack, which might lead to better bundles using only Vite or Rollup. But custom builds are not supported by KV yet, [apparently](https://github.com/frandiox/vitedge/pull/22).

One thing you can do is:
- Play with Webpack config `mainFields` (this is what I did the first time)
- Try disable dependencies you added recently until things work.

**Comment by subhendukundu** [comment]
I am still not able to fix it. Feels like out of my expertise. I went back to the place I remember I was able to deploy, But it just wouldn't work.
To get some help and make the build as you are getting `Error: Please specify a baseURL. More information at https://docs.nhost.io/libraries/nhost-js-sdk#setup`, can you take a pull again I have pushed two`.envexample` files.
One is in `/.envexample` and the other one `functions/.envexample`. Can you rename them to `.env` and do `yarn build`? That would fix it.
Tho I am not sure how to fix the deploying issue yet. Still digging.
