### ISSUE TITLE
Environment variables arent accessible in app level?

### ISSUE THREAD

**Issue by subhendukundu** [frandiox/vitedge#18]
I have added a `.env`  in root with
```
VITEDGE_TEST="hello world"
HELLO_TEST="hello world"
```
Then trying to access them in `src/App.jsx` like so
```
function App ({ router }) {
  console.log(process.env.VITEDGE_TEST, process.env.HELLO_TEST)
```
but both are undefined. Am I doing something wrong?

**Comment by frandiox** [comment]
@subhendukundu For the frontend env variables you need to follow Vite instructions: https://vitejs.dev/guide/env-and-mode.html#env-files

> only variables prefixed with `VITE_` are exposed

**Comment by subhendukundu** [comment]
Fair enough. But seems not working.
https://github.com/subhendukundu/cool-bio-analytics/blob/main/.env.example
This is what I have defined.
https://github.com/subhendukundu/cool-bio-analytics/blob/main/src/App.jsx#L190

**Comment by frandiox** [comment]
Are you running on mode `example`? Normally you would use `.env` or `.env.development` for the name of your files. Other than that, use `import.meta.env.VITE_XXX` int he frontend to access variables, that's the recommended way in Vite.

In backend it's still `process.env.VITEDGE_XXX` since that doesn't run on Vite.

**Comment by subhendukundu** [comment]
oh no, I have a `.gitignore` with the `.env`, so it wouldn’t push it. People usually push it with `.env.example` to give an example of how to use the `.env`. Sorry I forgot to mention that.

But `import.meta.env.VITE_XXX` did the trick. Didn't know about this one. Thank you.
