### ISSUE TITLE
JWT for local and worker both

### ISSUE THREAD

**Issue by subhendukundu** [frandiox/vitedge#27]
JWT is working on local when I am using `import jwt from "jsonwebtoken";` but not `import jwt from "@tsndr/cloudflare-worker-jwt";`. And in workers, it works the other way. 
I understand because both use different environments. Is there was we can make it work in both? Based on `process.env.NODE_ENV`? Thoughts?

**Comment by frandiox** [comment]
@subhendukundu You need to use packages that rely on WebCrypto, which is natively supported in CF Workers and can be polyfilled in Node. I didn't know about `@tsndr/cloudflare-worker-jwt` but I think it works with WebCrypto.

For the polyfill, simply install `node-webcrypto-ossl` as a dev-dependency in your `package.json`. Vitedge should detect it and polyfill it during development 👍

**Comment by subhendukundu** [comment]
Just to confirm, https://www.npmjs.com/package/webcrypto with a polyfill `node-webcrypto-ossl` would work on worker and nodejs both?
If not, can you please add a link to WebCrypto which you have used?

**Comment by frandiox** [comment]
The only one I've used is the one mentioned, https://www.npmjs.com/package/node-webcrypto-ossl

This is used only during development (in Node). When running in the browser or in CF Worker, it uses the native one.

**Comment by subhendukundu** [comment]
Gotcha! Let me playaround. :) Thank you again.

**Comment by subhendukundu** [comment]
https://nodejs.org/api/webcrypto.html

Turned out this is added after v15 :)

**Comment by subhendukundu** [comment]
Were you using `node-webcrypto-ossl` for `decode` and `verify` for HS256 as well?
If you have, give me an example? 🙈

**Comment by subhendukundu** [comment]
Okay, so I found out about `jsrsasign` which is working on local and should work on workers too cause I have tried it in web.
But breaking my head, cause it wouldnt let me deploy the app now. Again gotta find out whats wrong with this one. No permanent fix hah?


I am gonna leave this code, just incase someone trying implement something similar.

```
import jsrsasign from "jsrsasign";

export function doVerify(sJWT, key) {
    console.log(sJWT);
    const acceptField = {
        alg: ["HS256"],
    };

    let isValid = false;
    try {
        isValid = jsrsasign.KJUR.jws.JWS.verifyJWT(sJWT, key, acceptField);
    } catch (ex) {
        console.log("Error: " + ex);
        isValid = false;
    }
    return isValid;
}

export function doDecode(sJWT) {
    const a = sJWT.split(".");
    const uClaim = jsrsasign.b64utos(a[1]);

    const pClaim = jsrsasign.KJUR.jws.JWS.readSafeJSONString(uClaim);
    const sClaim = JSON.stringify(pClaim, null, "  ");
    return sClaim;
}
```
