### ISSUE TITLE
Importing dayjs will load SSR but crash when rendering in client

### ISSUE THREAD

**Issue by twhitson** [frandiox/vitedge#39]
When relying on a files that imports dayjs, the page will load SSR but then immediately all content on the page will disappear. Could be an issue with dayjs itself. Switching to luxon fixed the issue for me

**Comment by frandiox** [comment]
I could not reproduce this error. I tried adding DayJS to this repo's `examples/react` project and render DayJS in the DOM but it worked well both in Node.js and Worker.
Do you want to check again on your end?

**Comment by twhitson** [comment]
Going to close this as I can't replicate it anymore either.
