### ISSUE TITLE
Websocket APIs

### ISSUE THREAD

**Issue by subhendukundu** [frandiox/vitedge#50]
I am hoping this could be done as https://developers.cloudflare.com/workers/runtime-apis/websockets already supports it.
But not sure how to go about with Vitedge. Have you tried? What is your take on this one?

**Comment by frandiox** [comment]
All Workers APIs are supported in the `preview --build-watch` mode. In normal development mode, I'm implementing worker-specific APIs right now in master branch (KV, cache, etc). I didn't check websockets yet since this might need extra integration with Vite's WS module but I'll have a look at it.

**Comment by frandiox** [comment]
This should be available in 0.16 in the development mode as well: https://vitedge.js.org/recipes/cloudflare-workers.html#websockets
