### ISSUE TITLE
Hook into fetchPageProps() to display loading component?

### ISSUE THREAD

**Issue by elmarw** [frandiox/vitedge#57]
Is it possible to hook into fetchPageProps() to change the state while fetching the props on client side navigation? I would like to display a loading component in case it takes a bit too long.

I tried router.beforeEach() but its triggered after fetching props is finished.

**Comment by frandiox** [comment]
@elmarw From `0.16.2`, the request for page props is not awaited until `beforeResolve` guard. Therefore, you should be able to add `beforeEach` guards in the main hook to show loading state 👍
