### ISSUE TITLE
HTTP Status Codes

### ISSUE THREAD

**Issue by clampr** [frandiox/vitedge#60]
Hi all and thanks a lot for the great plugin! 👍 

I'm trying to prevent soft 404's when working with vitedge. I already managed to return an HTTP `404` status code using this code in `functions/props/NotFound.ts`:

```ts
import type { EdgeProps } from 'vitedge'
import { NotFoundError } from 'vitedge/errors'

export default <EdgeProps> {
  async handler() {
    throw new NotFoundError('Not Found')
  }
}
```

I tried with some non-existing pages on my website and they show the correct Vue view. The calls to the vitedge API also return 404. However, the Vue page itself still return a `200` status code. Is it possible to reflect the status code of the API response also on the Vue page?

**Comment by frandiox** [comment]
@clampr Hello! You mean the server-side rendered page for a missing route returns code 200, right?

For now, you can add this to your 404 Vue page component to make it work:

```html
<script>
import { useContext } from 'vitedge'

export default {
  setup() {
    if (import.meta.env.SSR) {
      const { writeResponse } = useContext()
      writeResponse({ status: 404 })
    }
  },
}
</script>
```

I'll give it a thought about having this automatically applied like we do with 302 code 🤔

**Comment by clampr** [comment]
Thanks @frandiox 🙂 It does exactly what I was looking for.

I guess it makes sense to apply these status codes automatically as it would be consistent with the redirects. Reading the docs I was expecting it to be applied automatically. But I don’t mind as your snippet does the job, too.

**Comment by frandiox** [comment]
@clampr This should be automatic from v0.16.4 🎉
