### ISSUE TITLE
Invalid module - code ERR_INVALID_MODULE_SPECIFIER

### ISSUE THREAD

**Issue by frandiox** [frandiox/vitedge#74]
This error is thrown when using Node >= 16.2 due to this breaking change: https://github.com/nodejs/node/pull/37468

Downgrade to 16.11 or 14 for now. This breaking change might be backported to 14 as well.

**Comment by alexturpin** [comment]
I seem to be getting the same problem on v14.18.2...

```
alext@Alex-Office MINGW64 ~/src/project (main)
$ npm run dev

> project@0.0.0 dev
> vitedge dev --ssr

(node:11816) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "file:///C:/Users/alext/src/project/node_modules/.bin/vite-ssr" 
    at new NodeError (internal/errors.js:322:7)
    at Loader.getFormat (internal/modules/esm/loader.js:118:13)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:20)
    at Loader.import (internal/modules/esm/loader.js:177:17)
    at Object.loadESM (internal/process/esm_loader.js:68:5)

alext@Alex-Office MINGW64 ~/src/project (main)
$ node --version
v14.18.2
```

And this is the day I pick to integrate Vitedge to my project 😅

**Comment by alexturpin** [comment]
Same error on v14.17.6, a different one for v14.16.1 and v.15.15.5. 

```
TypeError [ERR_INVALID_RETURN_PROPERTY_VALUE]: Expected string to be returned for the "format" from the "loader getFormat" function but got type object.
    at Loader.getFormat (internal/modules/esm/loader.js:111:13)
    at Loader.getModuleJob (internal/modules/esm/loader.js:231:20)
    at Loader.import (internal/modules/esm/loader.js:165:17)
    at Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by frandiox** [comment]
@alexturpin I'm not seeing the issue with latest 14 🤔 
Is your project using TS or JS?

**Comment by alexturpin** [comment]
@frandiox TypeScript. I also tried `ts-node` 10, 9 and 8 to no avail.

**Comment by frandiox** [comment]
@alexturpin 0.17.4 should have these issues fixed. Can you please give it a try?

**Comment by alexturpin** [comment]
@frandiox yes, thank you very much for the quick fix!

**Comment by mwoodruff** [comment]
I'm getting this error with reactesse-edge-template, regardless of node version. npm / yarn also makes no difference. Manual steps from the getting started page results in same. Running on windows.
