### ISSUE TITLE
Global cache config

### ISSUE THREAD

**Issue by m3hari** [frandiox/vitedge#82]
In our project, we don't use `page-props`  to avoid blocking UI after SPA takes over. Yet we want to leverage Cloudflare workers **cache** for server-rendered pages. Currently, we can achieve that using a placeholder page-props function to provide the cache configuration.

However, this approach doesn't really scale as we want to ssr several routes. Having several repeated placeholder page props with similar config feel a bit of code smell. 

A global "cache-config" in a file something like `vitedge.config.js` can simplify all this.  

Happy to provide a PR  with some assistance if this feature is  approved

**Comment by frandiox** [comment]
I'm not very keen to add a new file like `vitedge.config.js`, but perhaps we can pass the default cache options to the plugin in `vite.config.js` 🤔
