### ISSUE TITLE
Provide React starter template

### ISSUE THREAD

**Issue by subhendukundu** [frandiox/vitedge#9]
Are you planning on creating more of `create-vitedge-app`?
I can help on this one, let me know please about the plan.

**Comment by subhendukundu** [comment]
https://github.com/subhendukundu/vitedge-react-template
Got an error, `TypeError: Request is not a constructor`

**Comment by frandiox** [comment]
I didn't have anything in mind yet and in fact I don't have much time now, so it would be great indeed if you want to help with it.
Perhaps https://github.com/frandiox/vitessedge-template could help as inspiration for a template.

>Got an error, TypeError: Request is not a constructor

How do you get that error? I tried `yarn dev:ssr` in your repo but it seems to work well.

**Comment by subhendukundu** [comment]
Umm intersting. I was running the same. `yarn dev:ssr`.
Which platform you are using? Windows, Mac or Linux?
I am trying on Mac.

**Comment by frandiox** [comment]
Mac as well, with `node@14.16.0` and `yarn@1.22.0` 🤔

**Comment by subhendukundu** [comment]
Super weird!
`node@14.12.0` doesn't work. But works on `node@14.16.0`.

**Comment by subhendukundu** [comment]
@frandiox How would you add private routes?
For example, https://github.com/subhendukundu/vitedge-react-template/blob/main/src/App.jsx#L35
We have a login and homepage.
I want to do something, 
```
<AuthGate>
      <Route exact path="/">
            <Home />
       </Route>
</AuthGate>
```
Any recommendations?

**Comment by frandiox** [comment]
@subhendukundu What's the recommended way in plain React? I think it should work here as well.
In Vue you would just use the Router's `beforeEnter` guard but I don't think React's router has that. I believe you need to wrap your page components in some extra logic that checks the route.
More or less similar to what you are doing already but perhaps the `<AuthGate>` should be between `<Route>` and `<route.component />`, not sure. That should give you a "middleware" to run logic before the get-page-props logic.

Is there any problem with that? 🤔

**Comment by subhendukundu** [comment]
Well no, it works.
I would have done it in that way.
But I am not really happy about `if(!route.name === 'login') {` this part. Because for this case I have to maintain a list of unprotected routes.

For example,
```
const unprotectedRoutes = ['login', 'about', 'contact'];
<Switch>
    {router.routes.map((route) => {
    console.log(route);
    if(!unprotectedRoutes.includes(route.name)) {
        return (
        <Route exact key={route.path} path={route.path}>
            <route.component />
        </Route>
        );
    }
    return (
        <AuthGate>
          <Route exact key={route.path} path={route.path}>
              <route.component />
          </Route>
        </AuthGate>
    );
    })}
    <Redirect to="/" />
</Switch>

```
So I was wondering if there's a better way to do this or not.

**Comment by frandiox** [comment]
@subhendukundu I see! I would probably move all that logic inside the `AuthGate` component itself and pass it the `route` as props. Then, it can check if it renders children directly or makes some auth stuff first.

Another way to do this more declarative would be exporting a `const meta = { auth: true, ... }` from each page and pass it to the routes (`routes = [{ path, name, component, meta }]`). Then, you could access this in your AuthGate component. It might be a bit challenging making it work with lazy routes, though, since you would need this meta info eagerly before loading the page component.

**Comment by frandiox** [comment]
@subhendukundu Please tell me if you finish a React template so I can check it and add a link from Vitedge docs!

**Comment by subhendukundu** [comment]
I need a few input.

1. What if I don't want to use `.jsx` but want to use `.js`? How do I config that?

2. How do I use just `javascript` not `typescript`? Import wasn't working when I was just js. Do I need to add `.babelrc` or something like that?

**Comment by frandiox** [comment]
>1. What if I don't want to use .jsx but want to use .js? How do I config that?

That's not supported in Vite out of the box: https://github.com/vitejs/vite/issues/2727 |  https://twitter.com/youyuxi/status/1362050255009816577

>2. How do I use just javascript not typescript? Import wasn't working when I was just js. Do I need to add .babelrc or something like that?

Pure JavaScript relies on Node's native ESM support. Node cannot infer file extensions anymore so you need to provide full path with extension `import x from 'path/to/file.js'` or `'path/to/file/index.js'`

**Comment by subhendukundu** [comment]
I thought so.
So the easier fix is, keeping `tsconfig.json` and `vite.config.ts`. Then you can use them however you want to use them (javascript or typescript) :)
Cool. Then I guess we are good. Unless you want me to add few more things.

**Comment by frandiox** [comment]
Ah, I thought you were adding AuthGate and stuff like that since you asked about it in this issue.
I guess at least it should be deployed to workers.dev and have a readme explaining about how to set it up? And make it a "template project" in GitHub options so it can be cloned from there.

**Comment by subhendukundu** [comment]
Sure, I will add them. Just wanted to make sure what all you think we can add.
So this will definitely give a quick start.
I was thinking more of.
1. with-vitedge
2. with-auth-vitedge
3. with-nhost-vitedge

I will create a PR with these 3 examples for now. Also my whole example is open-sourced as well. So you can create a discord or github page like `built-with` or something.

**Comment by frandiox** [comment]
Ah I think we don't really need more examples in this repo, just templates in different repos that people can use as 1-click starters. The examples heres are mostly for manual testing until there are proper tests.

I think a good template could have dynamic routes and i18n (like [Vitessedge](https://github.com/frandiox/vitessedge-template) for Vue). And some auth-guarded routes would be 🔥 

We can add links to templates in the docs or in the readme.

**Comment by subhendukundu** [comment]
Sure! Coming a PR soon 👍

**Comment by subhendukundu** [comment]
I was working on this and someone reached out to me as well that after deploying it, the css wouldn't load.
https://vitedge.coolbio.workers.dev/

Repo: https://github.com/subhendukundu/vitedge-react-template

**Comment by frandiox** [comment]
@subhendukundu The Wrangler file is wrong. It is pointing to `dist/ssr` for the static assets instead of `dist/client` (`bucket = "../dist/client"`)

**Comment by subhendukundu** [comment]
Oh shoot! I changed in my other repo but forgot on this one 🥺
Thank you so much

**Comment by benjaminsehl** [comment]
Following this! Would love to play with it when ready @subhendukundu!
