### ISSUE TITLE
Get Cookies Headers during vitedge initializatio script

### ISSUE THREAD

**Issue by oleghalin** [frandiox/vitedge#91]
Hello. I'm trying to set i18n locale on the server-side, to do so I need to get the locale cookie from Request Headers. How can i access it in `vitedge` callback? 

<img width="855" alt="image" src="https://user-images.githubusercontent.com/9086983/178022436-58b1c566-b7cb-4048-a658-519f5290f9bb.png">

**Comment by frandiox** [comment]
Hi! You should be able to get the `request` object in the main hook: `export default vitedge(App, {...}, (context) => { context.request; ... });`

**Comment by oleghalin** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/9086983/178222071-e9306837-97e7-4016-a8a8-51ffeb527979.png">
And looks like types doesn't have it in request too.
